services:
    jwt.manager:
        public: true
        class: 'PhpSolution\JwtBundle\Jwt\JwtManager'
        arguments: ['@jwt.configuration_registry', '@jwt.token_type_registry']

    jwt.token_type_registry:
        public: false
        class: 'PhpSolution\JwtBundle\Jwt\Type\TypeRegistry'
        arguments: [~]

    jwt.configuration_registry:
        public: false
        class: 'PhpSolution\JwtBundle\Jwt\Configuration\ConfigRegistry'
        arguments: [~]